/*
	  Reimplementation of Binary Data found in "trial_camera.pak" in Danganronpa 2
	Not functional or efficient code, written recreationally for "fun" cause I
	forgot to bring my lunch to work so I wrote this instead.
	  The cameras don't actually point to a certain thing, for example, if you
	recreate "FIXED_00" in Blender, you will notice it pointing to where Twogami's
	spot would be in game, the OP Code that sets these Trial Cameras actually
	uses an index to point toward the characters, so you can't really export
	these and it takes extra math to have them work in a different game of yours.

	==== MORE INFO ====
		.pak files are basically just concatonated binary data blobs with some
	metadata for the location of the data.
		
		So how were these files made? I don't know, but the structure for this file
	is so easy that you can basically recreate it in code.
	
		This is not the same for all files, for stuff like "sv_test.pak", it's more
	like if you did `cat pak.metadata bar.tga menu.tga >> sv_test.pak`.
	
		Ultra Despair Girl actullay has some empty .h header files with pragma directives
	at the start, so it's most likely that these were made in a file like that
	too, however if not, they were probably just directly writing the binary
	to files named like FIXED_00.cam instead of what is done below.
	
		They most likely used .pak files instead of having a big ass table like this
	in the code because this takes a lot of memory, with them using .pak files, they
	can just read the necessary part they need when called and the dispose it. Why
	waste 69 KiB (0.21%) of memory when you can just load 60 B + 9 B when necessary only?
	
		I have recreated them as 2 arrays instead of Dictionary<string, TrialCameraStruct>
	because that's how they were stored in the .pak file and I wouldn't know how to
	union 2 arrays by reference either way.
	
		Someone actually went and documented what each camera does already
	https://docs.google.com/spreadsheets/d/1ewULVgmZAZ9urdq1nZHiRvUlW3bEwXk-6QgYqUSlKsM/
*/

// As revealed by the Symbols in the Anniversary version, this exists, however,
// I'm not gonna use it, I'm pretending it didn't exist
//public struct DrsVector3{public float X, Y, Z}

using System.Runtime.InteropServices;

class Program {
	private static readonly DR_TrialCam.TrialCameraStruct CameraSelect1 =
		DR_TrialCam.GetCameraData("FIXED_00");
	private static readonly DR_TrialCam.TrialCameraStruct CameraSelect2 =
		DR_TrialCam.GetCameraData(1);

	static void Main() {
		// Get Camera names starting with "ENO_"
		Console.WriteLine("Junko's Special Cams are: ");
		foreach (string CameraName in DR_TrialCam.GetCamerasNamesArray()) {
			if (CameraName.StartsWith("ENO_")) Console.Write($"{CameraName} ");
		}
		Console.Write("\n");

		Console.WriteLine();

		// you can't deserialize structs with JsonSerializer because fuck you
		/*
		// Deserialize them in JSON so it looks like cool
		JsonSerializerOptions SerializeOption = new JsonSerializerOptions{WriteIndented = true};
		string Ser1 = JsonSerializer.Serialize(CameraSelect1, SerializeOption);
		string Ser2 = JsonSerializer.Serialize(CameraSelect2, SerializeOption);
		Console.WriteLine("==== First Cam Struct ====");
		Console.WriteLine(Ser1);
		Console.WriteLine("==== Second Cam Struct ====");
		Console.WriteLine(Ser2);
		*/

		// Get random proprieties from the 2 cams I bothered to manually write
		int _index1 = 0;
		foreach (DR_TrialCam.TrialCameraStruct camera in DR_TrialCam.GetCamerasArray()) {
			Console.WriteLine($"==== Current Camera {_index1}");
			int _index2 = 0;
			foreach (DR_TrialCam.CameraPositionStruct keyframe in camera.Keyframes) {
				Console.WriteLine($"[Camera {_index1}] Keyframe index {_index2}");
				Console.WriteLine("[Camera {0}]\tXPos: {1}, YPos: {2}, ZPos: {3}\n\t\tXRot: {4}, YRot: {5}, ZRot: {6}",
									_index1, keyframe.X, keyframe.Y, keyframe.Z, keyframe.XRot, keyframe.YRot, keyframe.ZRot);
				_index2++;
			}
			_index1++;
		}

		Console.WriteLine();

		// Print const, look I'm running out of ideas of what to do here
		Console.WriteLine(DR_TrialCam.NUM_OF_CAMERAS);

		Console.WriteLine();


		Console.WriteLine();

		// Uhhhh... print the hex location of the array structs?????????
		Console.WriteLine(string.Format("0x{0:X}", CameraSelect1));
		Console.WriteLine(string.Format("0x{0:X}", CameraSelect2));
		// maybe also print the contents but memory stream has no easy way to
	}
}

public class DR_TrialCam {
	// magic number!
	public const int NUM_OF_CAMERAS = 860;

	// Why is this not a quaternion? Anyways this was most likely 2 DrsVector3
	[StructLayout(LayoutKind.Sequential), Serializable()]
	public struct CameraPositionStruct {

		// this could also be a primary constructor instead of a separate one
		public CameraPositionStruct
				(float x = 0, float y = 0, float z = 0, float xRot = 0, float yRot = 0, float zRot = 0) {
			this.ZRot = zRot;
			this.YRot = yRot;
			this.X = x;
			this.Y = y;
			this.Z = z;
			this.XRot = xRot;
		}


		// UNK: not XYZ Euler??? add 90 to XRot and ZRot to correct it in apps like Blender
		public float ZRot; // if not ZRot, this is possibly Yaw
		public float YRot; // if not YRot, this is possibly Pitch
		public float X, Y, Z; // in Danganronpa the 2nd parameter for the character player
							  // is up/down (YPos internally)
		public float XRot; // if not XRot, this is possibly Roll or Vector4 quaternion
	}

	[StructLayout(LayoutKind.Sequential, Pack = 4), Serializable()]
	public struct TrialCameraStruct {
		public TrialCameraStruct
				// should the array cam pos be declared as nullable?
				// actually, why should these even need defaults?
				(float unk1 = 0, float motionDuration = 0, CameraPositionStruct[] keyframes = null, short nextCam = 0, short _ = 0) {
			this.Unk1 = unk1;
			this.MotionDuration = motionDuration;
			this.Keyframes = keyframes;
			this.ShouldGoToTheNextCam = nextCam;
			this._Padding = 0;
		}

		public float Unk1; // 0-N, mostly 0.5, probably how much of it to play?
		public float MotionDuration; // for the camera that pans around Junko, the
									 // values are something like 0, 420, 470 for
									 // the 3 cameras used, so how many frames
									 // or start of keyframe
		public CameraPositionStruct[] Keyframes;
		public short ShouldGoToTheNextCam;	// if 0 then it stops, if 1 then it
											// goes to the next camera, if
											// short.MaxValue then it goes 
											// CurrentCameraID + 256
		public short _Padding; // always 0x00 0x00 so the file is 4 bytes aligned
							   // short or byte[2] both work
	}
	
	// e.g. DR_TrialCam.GetCameraData(1)
	public static TrialCameraStruct GetCameraData(int Index, bool PrintDebug = false) {
		if (PrintDebug) Console.WriteLine($"[GCD] {Index} - {Cameras[Index]}");
		return Cameras[Index];
	}

	// crashes if the string is incorrect lol
	// e.g. DR_TrialCam.GetCameraData("FIXED_00");
	public static TrialCameraStruct GetCameraData(string CameraName, bool PrintDebug = false) {
		if (PrintDebug) Console.WriteLine($"[GCD] {CameraName} - {Cameras[Array.IndexOf(CameraNames, CameraName)]}");
		return Cameras[Array.IndexOf(CameraNames, CameraName)];
	}

	public static TrialCameraStruct[] GetCamerasArray() {
		return Cameras;
	}

	public static string[] GetCamerasNamesArray() {
		return CameraNames;
	}

	// These were most likely set in Excel, also how to hell do I write these to
	// be much sexier???? I would have loved to just simpley write 
	// 		`{0.5, 180 {{0,0,13.4,30,20,0}, {0,0,13.4,30,20,0}}, 0, 0}`
	// but I can't, Also good thing these start at 0 and not 1 :^)
	private readonly static TrialCameraStruct[] Cameras = /* new TrialCameraStruct[NUM_OF_CAMERAS] { */ [
		/* FIXED_00	*/
		new TrialCameraStruct(0.5f, 180.0f,
			new CameraPositionStruct[] { new CameraPositionStruct(0.0f, 0.0f, 13.4f, 30.0f, 20.0f, 0.0f),
										 new CameraPositionStruct(0.0f, 0.0f, 13.4f, 30.0f, 20.0f, 0.0f) },
		0, 0),
		/* FIXED_01	*/
			// this also works like above, just easier to read... but it actually
			// isn't since you can't tell what the variables mean now
		new(0.5f, 180.0f, [ new(0.0f, 0.0f, 13.8f, 38.0f, 20.0f, 0.0f), new(0.0f, 0.0f, 13.8f, 38.0f, 20.0f, 0.0f) ], 0, 0),
		/* FIXED_02	*/
			// yeah i'm not doing the rest, you can make a Stream and use
			// BinaryReader to parse the rest, kind of sucks that there isn't a
			// strem.Read<TrialCameraStruct>() to make this easier, oh well
		/* FIXED_03	*/
		/* FIXED_04	*/
		// ...
	];

	// They most likely had comments with what all the cameras did
	private readonly static string[] CameraNames = /* new string[NUM_OF_CAMERAS] { */ [
		"FIXED_00",	// you might think this points at Hajime, but no, there aren't
					// 18 fixed spots, so these are something else
		"FIXED_01",
		"FIXED_02",
		"FIXED_03",
		"FIXED_04",
		"FIXED_05",
		"FIXED_06",
		"FIXED_07",
		"FIXED_08",
		"FIXED_09",
		"FIXED_10",
		"FIXED_11",
		"PAN_L_00",
		"PAN_L_01",
		"PAN_L_02",
		"PAN_L_03",
		"PAN_L_04",
		"PAN_L_05",
		"PAN_L_06",
		"PAN_L_07",
		"PAN_L_08",
		"PAN_L_09",
		"PAN_L_HIGH_00",
		"PAN_L_HIGH_01",
		"PAN_L_HIGH_02",
		"PAN_L_HIGH_03",
		"PAN_L_HIGH_04",
		"PAN_L_HIGH_05",
		"PAN_L_HIGH_06",
		"PAN_L_HIGH_07",
		"PAN_L_HIGH_08",
		"PAN_L_HIGH_09",
		"PAN_R_00",
		"PAN_R_01",
		"PAN_R_02",
		"PAN_R_03",
		"PAN_R_04",
		"PAN_R_05",
		"PAN_R_06",
		"PAN_R_07",
		"PAN_R_08",
		"PAN_R_09",
		"PAN_R_HIGH_00",
		"PAN_R_HIGH_01",
		"PAN_R_HIGH_02",
		"PAN_R_HIGH_03",
		"PAN_R_HIGH_04",
		"PAN_R_HIGH_05",
		"PAN_R_HIGH_06",
		"PAN_R_HIGH_07",
		"PAN_R_HIGH_08",
		"PAN_R_HIGH_09",
		"PAN_U_00",
		"PAN_U_01",
		"PAN_U_02",
		"PAN_U_03",
		"PAN_U_04",
		"PAN_U_05",
		"PAN_U_06",
		"PAN_U_07",
		"PAN_U_08",
		"PAN_U_09",
		"PAN_U_10",
		"PAN_U_11",
		"PAN_U_12",
		"PAN_U_13",
		"PAN_U_14",
		"PAN_U_15",
		"PAN_U_16",
		"PAN_U_17",
		"PAN_U_18",
		"PAN_D_00",
		"PAN_D_01",
		"PAN_D_02",
		"PAN_D_03",
		"PAN_D_04",
		"PAN_D_05",
		"PAN_D_06",
		"PAN_D_07",
		"PAN_D_08",
		"PAN_D_09",
		"PAN_D_10",
		"PAN_D_11",
		"PAN_D_12",
		"PAN_D_13",
		"PAN_D_14",
		"PAN_D_15",
		"PAN_L_OVER_00",
		"PAN_L_OVER_01",
		"PAN_L_OVER_02",
		"PAN_L_OVER_03",
		"PAN_L_OVER_04",
		"PAN_L_OVER_05",
		"PAN_L_OVER_06",
		"PAN_L_OVER_07",
		"PAN_L_OVER_08",
		"PAN_L_OVER_09",
		"PAN_L_OVER_10",
		"PAN_L_OVER_11",
		"PAN_L_OVER_12",
		"PAN_L_OVER_13",
		"PAN_L_OVER_14",
		"PAN_L_OVER_15",
		"PAN_L_OVER_16",
		"PAN_L_OVER_17",
		"PAN_L_OVER_18",
		"PAN_L_OVER_19",
		"PAN_L_OVER_20",
		"PAN_L_OVER_21",
		"PAN_L_OVER_22",
		"PAN_L_OVER_23",
		"PAN_L_OVER_24",
		"PAN_R_OVER_00",
		"PAN_R_OVER_01",
		"PAN_R_OVER_02",
		"PAN_R_OVER_03",
		"PAN_R_OVER_04",
		"PAN_R_OVER_05",
		"PAN_R_OVER_06",
		"PAN_R_OVER_07",
		"PAN_R_OVER_08",
		"PAN_R_OVER_09",
		"PAN_R_OVER_10",
		"PAN_R_OVER_11",
		"PAN_R_OVER_12",
		"PAN_R_OVER_13",
		"PAN_R_OVER_14",
		"PAN_R_OVER_15",
		"PAN_R_OVER_16",
		"PAN_R_OVER_17",
		"PAN_R_OVER_18",
		"PAN_R_OVER_19",
		"PAN_R_OVER_20",
		"PAN_R_OVER_21",
		"PAN_R_OVER_22",
		"PAN_R_OVER_23",
		"PAN_R_OVER_24",
		"DOLLYIN_00",
		"DOLLYIN_01",
		"DOLLYIN_02",
		"DOLLYIN_03",
		"DOLLYIN_04",
		"DOLLYIN_05",
		"DOLLYIN_06",
		"DOLLYIN_07",
		"DOLLYIN_08",
		"DOLLYIN_09",
		"DOLLYIN_10",
		"DOLLYIN_11",
		"DOLLYIN_12",
		"DOLLYIN_13",
		"DOLLYIN_14",
		"DOLLYIN_15",
		"DOLLYIN_16",
		"DOLLYIN_17",
		"DOLLYIN_18",
		"DOLLYIN_19",
		"DOLLYBACK_00",
		"DOLLYBACK_01",
		"DOLLYBACK_02",
		"DOLLYBACK_03",
		"DOLLYBACK_04",
		"DOLLYBACK_05",
		"DOLLYBACK_06",
		"DOLLYBACK_07",
		"DOLLYBACK_08",
		"DOLLYBACK_09",
		"DOLLYBACK_10",
		"DOLLYBACK_11",
		"DOLLYBACK_12",
		"DOLLYBACK_13",
		"DOLLYBACK_14",
		"DOLLYBACK_15",
		"DOLLYBACK_16",
		"DOLLYBACK_17",
		"DOLLYBACK_18",
		"DOLLYBACK_19",
		"DOLLYUP_00",
		"DOLLYUP_01",
		"DOLLYUP_02",
		"DOLLYUP_03",
		"DOLLYUP_04",
		"DOLLYUP_05",
		"DOLLYUP_06",
		"DOLLYUP_07",
		"DOLLYUP_08",
		"DOLLYUP_09",
		"DOLLYDOWN_00",
		"DOLLYDOWN_01",
		"DOLLYDOWN_02",
		"DOLLYDOWN_03",
		"DOLLYDOWN_04",
		"DOLLYDOWN_05",
		"DOLLYDOWN_06",
		"DOLLYDOWN_07",
		"DOLLYDOWN_08",
		"DOLLYDOWN_09",
		"ZOOMIN_00",
		"ZOOMIN_01",
		"ZOOMIN_02",
		"ZOOMIN_03",
		"ZOOMIN_04",
		"ZOOMIN_05",
		"ZOOMIN_06",
		"ZOOMIN_07",
		"ZOOMIN_08",
		"ZOOMIN_09",
		"ZOOMIN_10",
		"ZOOMOUT_00",
		"ZOOMOUT_01",
		"ZOOMOUT_02",
		"ZOOMOUT_03",
		"ZOOMOUT_04",
		"ZOOMOUT_05",
		"ZOOMOUT_06",
		"ZOOMOUT_07",
		"ZOOMOUT_08",
		"ZOOMOUT_09",
		"ZOOMOUT_10",
		"ZOOMIN_DOLLYBACK_00",
		"ZOOMIN_DOLLYBACK_01",
		"ZOOMIN_DOLLYBACK_02",
		"ZOOMIN_DOLLYBACK_03",
		"ZOOMIN_DOLLYBACK_03_END",
		"ZOOMIN_DOLLYBACK_04",
		"ZOOMIN_DOLLYBACK_04_END",
		"ZOOMOUT_DOLLYIN_00",
		"ZOOMOUT_DOLLYIN_01",
		"ZOOMOUT_DOLLYIN_02",
		"ZOOMOUT_DOLLYIN_03",
		"ZOOMOUT_DOLLYIN_03_END",
		"ZOOMOUT_DOLLYIN_04",
		"ZOOMOUT_DOLLYIN_04_END",
		"Q_PAN_L_00",	// some of the cameras from above but with Q_ at the start
						// since these aren't a nice number away like 128, these
						// were probably made manually and jumped to manually
		"Q_PAN_L_00_END",
		"Q_PAN_L_01",
		"Q_PAN_L_01_END",
		"Q_PAN_L_02",
		"Q_PAN_L_02_END",
		"Q_PAN_L_03",
		"Q_PAN_L_03_END",
		"Q_PAN_L_04",
		"Q_PAN_L_04_END",
		"Q_PAN_L_05",
		"Q_PAN_L_05_END",
		"Q_PAN_L_06",
		"Q_PAN_L_06_END",
		"Q_PAN_L_07",
		"Q_PAN_L_07_END",
		"Q_PAN_L_08",
		"Q_PAN_L_08_END",
		"Q_PAN_L_09",
		"Q_PAN_L_09_END",
		"Q_PAN_R_00",
		"Q_PAN_R_00_END",
		"Q_PAN_R_01",
		"Q_PAN_R_01_END",
		"Q_PAN_R_02",
		"Q_PAN_R_02_END",
		"Q_PAN_R_03",
		"Q_PAN_R_03_END",
		"Q_PAN_R_04",
		"Q_PAN_R_04_END",
		"Q_PAN_R_05",
		"Q_PAN_R_05_END",
		"Q_PAN_R_06",
		"Q_PAN_R_06_END",
		"Q_PAN_R_07",
		"Q_PAN_R_07_END",
		"Q_PAN_R_08",
		"Q_PAN_R_08_END",
		"Q_PAN_R_09",
		"Q_PAN_R_09_END",
		"Q_DOLLYUP_00",
		"Q_DOLLYUP_00_END",
		"Q_DOLLYUP_01",
		"Q_DOLLYUP_01_END",
		"Q_DOLLYUP_02",
		"Q_DOLLYUP_02_END",
		"Q_DOLLYUP_03",
		"Q_DOLLYUP_03_END",
		"Q_DOLLYUP_04",
		"Q_DOLLYUP_04_END",
		"Q_DOLLYDOWN_00",
		"Q_DOLLYDOWN_00_END",
		"Q_DOLLYDOWN_01",
		"Q_DOLLYDOWN_01_END",
		"Q_DOLLYDOWN_02",
		"Q_DOLLYDOWN_02_END",
		"Q_DOLLYDOWN_03",
		"Q_DOLLYDOWN_03_END",
		"Q_DOLLYDOWN_04",
		"Q_DOLLYDOWN_04_END",
		"Q_ZOOMIN_00",
		"Q_ZOOMIN_00_END",
		"Q_ZOOMIN_01",
		"Q_ZOOMIN_01_END",
		"Q_ZOOMIN_02",
		"Q_ZOOMIN_02_END",
		"Q_ZOOMIN_03",
		"Q_ZOOMIN_03_END",
		"Q_ZOOMIN_04",
		"Q_ZOOMIN_04_END",
		"Q_ZOOMIN_05",
		"Q_ZOOMIN_05_END",
		"Q_ZOOMIN_06",
		"Q_ZOOMIN_06_END",
		"Q_ZOOMOUT_00",
		"Q_ZOOMOUT_00_END",
		"Q_ZOOMOUT_01",
		"Q_ZOOMOUT_01_END",
		"Q_ZOOMOUT_02",
		"Q_ZOOMOUT_02_END",
		"Q_ZOOMOUT_03",
		"Q_ZOOMOUT_03_END",
		"Q_ZOOMOUT_04",
		"Q_ZOOMOUT_04_END",
		"Q_ZOOMOUT_05",
		"Q_ZOOMOUT_05_END",
		"Q_ZOOMOUT_06",
		"Q_ZOOMOUT_06_END",
		"F_PAN_L_00", // for some reason the cameras from before repeated again,
					  // F_ most likely stands for Fast, Q_ stands for Quacamole
		"F_PAN_L_01",
		"F_PAN_L_02",
		"F_PAN_L_03",
		"F_PAN_L_04",
		"F_PAN_L_05",
		"F_PAN_L_06",
		"F_PAN_L_07",
		"F_PAN_L_08",
		"F_PAN_L_09",
		"F_PAN_L_HIGH_00",
		"F_PAN_L_HIGH_01",
		"F_PAN_L_HIGH_02",
		"F_PAN_L_HIGH_03",
		"F_PAN_L_HIGH_04",
		"F_PAN_L_HIGH_05",
		"F_PAN_L_HIGH_06",
		"F_PAN_L_HIGH_07",
		"F_PAN_L_HIGH_08",
		"F_PAN_L_HIGH_09",
		"F_PAN_R_00",
		"F_PAN_R_01",
		"F_PAN_R_02",
		"F_PAN_R_03",
		"F_PAN_R_04",
		"F_PAN_R_05",
		"F_PAN_R_06",
		"F_PAN_R_07",
		"F_PAN_R_08",
		"F_PAN_R_09",
		"F_PAN_R_HIGH_00",
		"F_PAN_R_HIGH_01",
		"F_PAN_R_HIGH_02",
		"F_PAN_R_HIGH_03",
		"F_PAN_R_HIGH_04",
		"F_PAN_R_HIGH_05",
		"F_PAN_R_HIGH_06",
		"F_PAN_R_HIGH_07",
		"F_PAN_R_HIGH_08",
		"F_PAN_R_HIGH_09",
		"F_PAN_U_00",
		"F_PAN_U_01",
		"F_PAN_U_02",
		"F_PAN_U_03",
		"F_PAN_U_04",
		"F_PAN_U_05",
		"F_PAN_U_06",
		"F_PAN_U_07",
		"F_PAN_U_08",
		"F_PAN_U_09",
		"F_PAN_U_10",
		"F_PAN_U_11",
		"F_PAN_U_12",
		"F_PAN_U_13",
		"F_PAN_U_14",
		"F_PAN_U_15",
		"F_PAN_U_16",
		"F_PAN_U_17",
		"F_PAN_U_18",
		"F_PAN_D_00",
		"F_PAN_D_01",
		"F_PAN_D_02",
		"F_PAN_D_03",
		"F_PAN_D_04",
		"F_PAN_D_05",
		"F_PAN_D_06",
		"F_PAN_D_07",
		"F_PAN_D_08",
		"F_PAN_D_09",
		"F_PAN_D_10",
		"F_PAN_D_11",
		"F_PAN_D_12",
		"F_PAN_D_13",
		"F_PAN_D_14",
		"F_PAN_D_15",
		"F_PAN_L_OVER_00",
		"F_PAN_L_OVER_01",
		"F_PAN_L_OVER_02",
		"F_PAN_L_OVER_03",
		"F_PAN_L_OVER_04",
		"F_PAN_L_OVER_05",
		"F_PAN_L_OVER_06",
		"F_PAN_L_OVER_07",
		"F_PAN_L_OVER_08",
		"F_PAN_L_OVER_09",
		"F_PAN_L_OVER_10",
		"F_PAN_L_OVER_11",
		"F_PAN_L_OVER_12",
		"F_PAN_L_OVER_13",
		"F_PAN_L_OVER_14",
		"F_PAN_L_OVER_15",
		"F_PAN_L_OVER_16",
		"F_PAN_L_OVER_17",
		"F_PAN_L_OVER_18",
		"F_PAN_L_OVER_19",
		"F_PAN_L_OVER_20",
		"F_PAN_L_OVER_21",
		"F_PAN_L_OVER_22",
		"F_PAN_L_OVER_23",
		"F_PAN_L_OVER_24",
		"F_PAN_R_OVER_00",
		"F_PAN_R_OVER_01",
		"F_PAN_R_OVER_02",
		"F_PAN_R_OVER_03",
		"F_PAN_R_OVER_04",
		"F_PAN_R_OVER_05",
		"F_PAN_R_OVER_06",
		"F_PAN_R_OVER_07",
		"F_PAN_R_OVER_08",
		"F_PAN_R_OVER_09",
		"F_PAN_R_OVER_10",
		"F_PAN_R_OVER_11",
		"F_PAN_R_OVER_12",
		"F_PAN_R_OVER_13",
		"F_PAN_R_OVER_14",
		"F_PAN_R_OVER_15",
		"F_PAN_R_OVER_16",
		"F_PAN_R_OVER_17",
		"F_PAN_R_OVER_18",
		"F_PAN_R_OVER_19",
		"F_PAN_R_OVER_20",
		"F_PAN_R_OVER_21",
		"F_PAN_R_OVER_22",
		"F_PAN_R_OVER_23",
		"F_PAN_R_OVER_24",
		"F_DOLLYIN_00",
		"F_DOLLYIN_01",
		"F_DOLLYIN_02",
		"F_DOLLYIN_03",
		"F_DOLLYIN_04",
		"F_DOLLYIN_05",
		"F_DOLLYIN_06",
		"F_DOLLYIN_07",
		"F_DOLLYIN_08",
		"F_DOLLYIN_09",
		"F_DOLLYIN_10",
		"F_DOLLYIN_11",
		"F_DOLLYIN_12",
		"F_DOLLYIN_13",
		"F_DOLLYIN_14",
		"F_DOLLYIN_15",
		"F_DOLLYIN_16",
		"F_DOLLYIN_17",
		"F_DOLLYIN_18",
		"F_DOLLYIN_19",
		"F_DOLLYBACK_00",
		"F_DOLLYBACK_01",
		"F_DOLLYBACK_02",
		"F_DOLLYBACK_03",
		"F_DOLLYBACK_04",
		"F_DOLLYBACK_05",
		"F_DOLLYBACK_06",
		"F_DOLLYBACK_07",
		"F_DOLLYBACK_08",
		"F_DOLLYBACK_09",
		"F_DOLLYBACK_10",
		"F_DOLLYBACK_11",
		"F_DOLLYBACK_12",
		"F_DOLLYBACK_13",
		"F_DOLLYBACK_14",
		"F_DOLLYBACK_15",
		"F_DOLLYBACK_16",
		"F_DOLLYBACK_17",
		"F_DOLLYBACK_18",
		"F_DOLLYBACK_19",
		"ROLL_L_00",
		"ROLL_L_01",
		"ROLL_L_02",
		"ROLL_L_03",
		"ROLL_L_04",
		"ROLL_L_05",
		"ROLL_L_06",
		"ROLL_L_07",
		"ROLL_L_08",
		"ROLL_L_09",
		"ROLL_L_10",
		"ROLL_L_11",
		"ROLL_L_12",
		"ROLL_L_12_END",
		"ROLL_L_13",
		"ROLL_L_14",
		"ROLL_R_00",
		"ROLL_R_01",
		"ROLL_R_02",
		"ROLL_R_03",
		"ROLL_R_04",
		"ROLL_R_05",
		"ROLL_R_06",
		"ROLL_R_07",
		"ROLL_R_08",
		"ROLL_R_09",
		"ROLL_R_10",
		"ROLL_R_11",
		"ROLL_R_12",
		"ROLL_R_12_END",
		"ROLL_R_13",
		"ROLL_R_14",
		"LOOKOUT_00",
		"LOOKOUT_01",
		"LOOKOUT_02",
		"LOOKOUT_03",
		"LOOKOUT_04",
		"LOOKOUT_05",
		"LOOKOUT_06",
		"LOOKOUT_07",
		"LOOKOUT_08",
		"MONOKUMA_SPEEK_00",
		"MONOKUMA_SPEEK_01",
		"MONOKUMA_SPEEK_02",
		"MONOKUMA_SPEEK_02_END",
		"MONOKUMA_SPEEK_03",
		"MONOKUMA_SPEEK_03_END",
		"MONOKUMA_SPEEK_04",
		"MONOKUMA_SPEEK_04_END",
		"MONOKUMA_SPEEK_05",
		"MONOKUMA_SPEEK_05_END",
		"MONOKUMA_SPEEK_06",
		"MONOKUMA_SPEEK_06_END",
		"MONOKUMA_SPEEK_07",
		"MONOKUMA_SPEEK_07_END",
		"MONOKUMA_SPEEK_08",
		"MONOKUMA_SPEEK_08_END",
		"MONOKUMA_SPEEK_09",
		"MONOKUMA_SPEEK_09_END",
		"MONOKUMA_SPEEK_10",
		"MONOKUMA_SPEEK_10_END",
		"MONOKUMA_SPEEK_11",
		"MONOKUMA_SPEEK_11_END",
		"MONOKUMA_SPEEK_12",
		"MONOKUMA_SPEEK_12_END",
		"MONOKUMA_SPEEK_13",
		"MONOKUMA_SPEEK_13_END",
		"MONOKUMA_SPEEK_14",
		"MONOKUMA_SPEEK_14_END",
		"MONOKUMA_SPEEK_15",
		"MONOKUMA_SPEEK_16",
		"MONOKUMA_SPEEK_17",
		"MONOKUMA_SPEEK_18",
		"MONOKUMA_SPEEK_19",
		"MONOKUMA_SPEEK_20",
		"MONOKUMA_SPEEK_21",
		"MONOKUMA_SPEEK_22",
		"MONOKUMA_SPEEK_23",
		"MONOKUMA_SPEEK_24",
		"MONOKUMA_SPEEK_25",
		"MONOKUMA_SPEEK_26",
		"MONOKUMA_SPEEK_27",
		"MONOKUMA_SPEEK_28",
		"MONOKUMA_SPEEK_29",
		"MONOKUMA_SPEEK_30",
		"MONOKUMA_SPEEK_31",
		"MONOKUMA_SPEEK_32",
		"MONOKUMA_SPEEK_33",
		"MONOKUMA_SPEEK_34",
		"MONOKUMA_SPEEK_35",
		"MONOKUMA_SPEEK_36",
		"MONOKUMA_SPEEK_37",
		"MONOKUMA_SPEEK_38",
		"MONOKUMA_SPEEK_39",
		"MONOKUMA_SPEEK_40",
		"MONOKUMA_SPEEK_41",
		"MONOKUMA_SPEEK_42",
		"MONOKUMA_SPEEK_43",
		"MONOKUMA_SPEEK_44",
		"MONOKUMA_SPEEK_45",
		"MONOKUMA_SPEEK_46",
		"MONOKUMA_SPEEK_47",
		"MONOKUMA_SPEEK_47_END",
		"MONOMI_SPEEK_00",
		"MONOMI_SPEEK_01",
		"MONOMI_SPEEK_02",
		"MONOMI_SPEEK_02_END",
		"MONOMI_SPEEK_03",
		"MONOMI_SPEEK_03_END",
		"MONOMI_SPEEK_04",
		"MONOMI_SPEEK_04_END",
		"MONOMI_SPEEK_05",
		"MONOMI_SPEEK_05_END",
		"MONOMI_SPEEK_06",
		"MONOMI_SPEEK_06_END",
		"MONOMI_SPEEK_07",
		"MONOMI_SPEEK_07_END",
		"MONOMI_SPEEK_08",
		"MONOMI_SPEEK_08_END",
		"MONOMI_SPEEK_09",
		"MONOMI_SPEEK_09_END",
		"MONOMI_SPEEK_10",
		"MONOMI_SPEEK_10_END",
		"MONOMI_SPEEK_11",
		"MONOMI_SPEEK_11_END",
		"MONOMI_SPEEK_12",
		"MONOMI_SPEEK_12_END",
		"MONOMI_SPEEK_13",
		"MONOMI_SPEEK_13_END",
		"MONOMI_SPEEK_14",
		"MONOMI_SPEEK_14_END",
		"MONOMI_SPEEK_15",
		"MONOMI_SPEEK_16",
		"MONOMI_SPEEK_17",
		"MONOMI_SPEEK_18",
		"MONOMI_SPEEK_19",
		"MONOMI_SPEEK_20",
		"MONOMI_SPEEK_21",
		"MONOMI_SPEEK_22",
		"MONOMI_SPEEK_23",
		"MONOMI_SPEEK_24",
		"MONOMI_SPEEK_25",
		"MONOMI_SPEEK_26",
		"MONOMI_SPEEK_27",
		"MONOMI_SPEEK_28",
		"MONOMI_SPEEK_29",
		"MONOMI_SPEEK_30",
		"MONOMI_SPEEK_31",
		"MONOMI_SPEEK_32",
		"MONOMI_SPEEK_33",
		"MONOMI_SPEEK_34",
		"MONOMI_SPEEK_35",
		"MONOMI_SPEEK_36",
		"MONOMI_SPEEK_37",
		"MONOMI_SPEEK_38",
		"MONOMI_SPEEK_39",
		"MONOMI_SPEEK_40",
		"MONOMI_SPEEK_41",
		"MONOMI_SPEEK_42",
		"MONOMI_SPEEK_43",
		"MONOMI_SPEEK_44",
		"MONOMI_SPEEK_45",
		"MONOMI_SPEEK_46",
		"MONOMI_SPEEK_47",
		"MONOMI_SPEEK_47_END",
		"MONOMI_SPEEK_48",
		"LOOK_AT_PAN_L_00",
		"LOOK_AT_PAN_L_01",
		"LOOK_AT_PAN_L_02",
		"LOOK_AT_PAN_L_03",
		"LOOK_AT_PAN_L_04",
		"LOOK_AT_PAN_L_05",
		"LOOK_AT_PAN_L_06",
		"LOOK_AT_PAN_L_07",
		"LOOK_AT_PAN_L_08",
		"LOOK_AT_PAN_L_09",
		"LOOK_AT_PAN_L_10",
		"LOOK_AT_PAN_L_11",
		"LOOK_AT_PAN_L_12",
		"LOOK_AT_PAN_L_13",
		"LOOK_AT_PAN_R_00",
		"LOOK_AT_PAN_R_01",
		"LOOK_AT_PAN_R_02",
		"LOOK_AT_PAN_R_03",
		"LOOK_AT_PAN_R_04",
		"LOOK_AT_PAN_R_05",
		"LOOK_AT_PAN_R_06",
		"LOOK_AT_PAN_R_07",
		"LOOK_AT_PAN_R_08",
		"LOOK_AT_PAN_R_09",
		"LOOK_AT_PAN_R_10",
		"LOOK_AT_PAN_R_11",
		"LOOK_AT_PAN_R_12",
		"LOOK_AT_PAN_R_13",
		"LOOK_AT_PAN_U_00",
		"LOOK_AT_PAN_U_01",
		"LOOK_AT_PAN_U_02",
		"LOOK_AT_PAN_U_03",
		"LOOK_AT_PAN_U_04",
		"LOOK_AT_PAN_U_05",
		"LOOK_AT_PAN_U_06",
		"LOOK_AT_PAN_U_07",
		"LOOK_AT_PAN_U_08",
		"LOOK_AT_PAN_D_00",
		"LOOK_AT_PAN_D_01",
		"LOOK_AT_PAN_D_02",
		"LOOK_AT_PAN_D_03",
		"LOOK_AT_PAN_D_04",
		"LOOK_AT_PAN_D_05",
		"LOOK_AT_PAN_D_06",
		"LOOK_AT_PAN_D_07",
		"LOOK_AT_PAN_D_08",
		"SAIBAN_START_00",
		"SAIBAN_START_01",
		"SAIBAN_START_01_N1",
		"SAIBAN_START_01_END",
		"SAIBAN_START_02",
		"SAIBAN_START_02_END",
		"SAIBAN_FUKKI_00",
		"SAIBAN_FUKKI_00_END",
		"GIRON_START_00",
		"GIRON_START_00_END",
		"GIRON_START_01",
		"GIRON_START_01_END",
		"GIRON_CHARGE_00",
		"GIRON_CHARGE_01",
		"GIRON_FINISH_00",
		"GIRON_FINISH_00_END",
		"GIRON_FINISH_01",
		"GIRON_FINISH_01_END",
		"MTB_START_00",
		"MTB_FINISH_00",
		"MTB_FINISH_00_N1",
		"MTB_FINISH_00_N2",
		"MTB_FINISH_00_END",
		"HANRON_START_L_00",
		"HANRON_START_L_00_END",
		"HANRON_START_R_00",
		"HANRON_START_R_00_END",
		"ANAGRAM_START_00",
		"KOKORO_00",
		"KOKORO_01",
		"KOKORO_02",
		"HANRON_00",
		"HANRON_01",
		"HANRON_02",
		"HANRON_03",
		"F_DOLLYUP_00",
		"F_DOLLYUP_01",
		"F_DOLLYUP_02",
		"F_DOLLYUP_03",
		"F_DOLLYUP_04",
		"F_DOLLYUP_05",
		"F_DOLLYDOWN_00",
		"F_DOLLYDOWN_01",
		"F_DOLLYDOWN_02",
		"F_DOLLYDOWN_03",
		"F_DOLLYDOWN_04",
		"F_DOLLYDOWN_05",
		"ZOOMIN_DOLLYBACK_05",
		"ZOOMIN_DOLLYBACK_05_END",
		"ZOOMIN_DOLLYBACK_06",
		"ZOOMIN_DOLLYBACK_06_END",
		"SAIBAN_KAIWA_OUT",
		"SAIBAN_KAIWA_OUT_END",
		"ENO_DOLLYIN_00",	// This might come as no surprise but ENO_ stands for Junko
		"ENO_DOLLYIN_01",
		"ENO_DOLLYIN_02",
		"ENO_ZOOMIN_00",
		"ENO_ZOOMIN_01",
		"ENO_ZOOMIN_02",
		"ENO_ZOOMIN_03",
		"ENO_ZOOMIN_04",
		"ENO_ZOOMIN_05",
		"ENO_ZOOMIN_06",
		"ENO_ZOOMIN_07",
		"ENO_ZOOMIN_08",
		"ENO_ZOOMOUT_00",
		"ENO_ZOOMOUT_01",
		"ENO_ZOOMOUT_02",
		"ENO_ZOOMOUT_03",
		"ENO_ZOOMOUT_04",
		"ENO_ZOOMOUT_05",
		"ENO_ZOOMOUT_06",
		"ENO_ZOOMOUT_07",
		"ENO_ZOOMOUT_08",
		"ENO_PAN_L_00",
		"ENO_PAN_L_01",
		"ENO_PAN_L_02",
		"ENO_PAN_L_03",
		"ENO_PAN_L_04",
		"ENO_PAN_L_05",
		"ENO_PAN_L_06",
		"ENO_PAN_L_07",
		"ENO_PAN_L_08",
		"ENO_PAN_L_09",
		"ENO_PAN_L_10",
		"ENO_PAN_L_11",
		"ENO_PAN_R_00",
		"ENO_PAN_R_01",
		"ENO_PAN_R_02",
		"ENO_PAN_R_03",
		"ENO_PAN_R_04",
		"ENO_PAN_R_05",
		"ENO_PAN_R_06",
		"ENO_PAN_R_07",
		"ENO_PAN_R_08",
		"ENO_PAN_R_09",
		"ENO_PAN_R_10",
		"ENO_PAN_R_11",
		"ENO_ZOOMOUT_DOLLYIN_00",
		"ENO_ZOOMOUT_DOLLYIN_01",
		"ENO_ZOOMOUT_DOLLYIN_02",
		"ENO_Q_ZOOMIN_00",
		"ENO_Q_ZOOMIN_01",
		"ENO_Q_ZOOMIN_02",
		"ENO_Q_ZOOMIN_03",
		"ENO_Q_ZOOMIN_04",
		"ENO_Q_ZOOMIN_05",
		"ENO_Q_ZOOMIN_06",
		"ENO_Q_ZOOMIN_07",
		"ENO_Q_ZOOMIN_08",
		"ENO_Q_ZOOMIN_09",
		"ENO_Q_ZOOMOUT_00",
		"ENO_Q_ZOOMOUT_01",
		"ENO_Q_ZOOMOUT_02",
		"ENO_Q_ZOOMOUT_03",
		"ENO_Q_ZOOMOUT_04",
		"ENO_Q_ZOOMOUT_05",
		"ENO_Q_ZOOMOUT_06",
		"ENO_Q_ZOOMOUT_07",
		"ENO_Q_ZOOMOUT_08",
		"ENO_Q_ZOOMOUT_09",
		"ENO_KYOMU_00",
		"ENO_KYOMU_01",
		"ENO_KYOMU_02",
		"ENO_KEITAI_00",
		"ENO_KEITAI_00_N1",
		"ENO_KEITAI_00_N2",
		"ENO_KEITAI_00_END",
		"ENO_TOUJYO_00",
		"ENO_TOUJYO_01",
		"ENO_TOUJYO_02",
		"ENO_TOUJYO_03",
		"ENO_HINATA_00",
		"ENO_HINATA_00_N1",
		"ENO_HINATA_00_END",
		"ENO_ARTA_00",
		"ENO_ARTA_01",
		"ENO_ARTA_02",
		"ENO_LOOK_AT_PAN_R_00",
		"SAIBAN_START_03",
		"SAIBAN_START_03_END",
		"ENO_TOUJYO_04",
		"ENO_TOUJYO_04_END",
		"SPECIAL_00",
		"SPECIAL_01",
		"SPECIAL_02",
		"SPECIAL_03",
		"SPECIAL_04",
		"SPECIAL_05",
		"SPECIAL_06",
		"SPECIAL_07",
		"SPECIAL_07_END",
		"SPECIAL_08",
		"SPECIAL_08_N1",
		"SPECIAL_08_END",
		"SPECIAL_09",
		"SPECIAL_09_N1",
		"SPECIAL_09_END",
		"SPECIAL_10",
		"SPECIAL_10_N1",
		"SPECIAL_10_N2",
		"SPECIAL_10_END"
	];
}
